language: python
python:
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev
  - sudo apt-get install -qq libpq-dev libtiff4-dev libjpeg8-dev libfreetype6-dev
  - sudo apt-get install -qq liblcms1-dev libwebp-dev graphviz-dev python-setuptools
  - sudo apt-get install -qq python3-dev python-virtualenv python-pip python3-pip
  - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev
  - sudo apt-get install -qq libreadline-dev libsqlite3-dev libxml2 libxml2-dev
  - sudo apt-get install -qq libssl-dev libbz2-dev wget curl llvm
install:
  - "pip install -r requeriments/local.txt"
